name: continuous integration
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'release/**'
      - 'develop**'

env:
  APP_NAME: ${{ github.event.repository.name }}
  ARTIFACTORY_SAAS_USERNAME: ${{ secrets.ARTIFACTORY_SAAS_USERNAME }}
  ARTIFACTORY_EDGE_TOKEN: ${{ secrets.ARTIFACTORY_EDGE_TOKEN }}
  ARTIFACTORY_SAAS_TOKEN: ${{ secrets.ARTIFACTORY_SAAS_TOKEN }}

jobs:
  build:
    name: build and publish
    runs-on: [ aks ]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          overwrite-settings: true
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.6.3
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2.0.0

      - name: Publish to Artifactory
        run: |
          tagName="FINAL"
          if ${{ github.ref_name != 'master' }}; then
            tagName="SNAPSHOT"
          fi
          jfrog config add --url=https://krogertechnology.jfrog.io --user=${{env.ARTIFACTORY_SAAS_USERNAME}} --password=${{env.ARTIFACTORY_SAAS_TOKEN}} --interactive=false artifactory
          jfrog rt mvn-config --repo-deploy-releases kroger-software-engineering --repo-deploy-snapshots kroger-software-engr-snap
          jfrog rt mvn clean install --settings settings.xml --build-name $GITHUB_REPOSITORY --build-number $GITHUB_RUN_ID-$GITHUB_RUN_NUMBER -Dsnapshot.tag=$tagName
